APP_SECRET=mC51FshIdGDafgPuxnfXGLrzzlccbZKK
DB_URL=mongodb://localhost:27117/wallet_payment_service_db
PORT=8001
KAFKA_BOOTSTRAP_SERVER=localhost:29092
FLUTTERWAVE_PUB_KEY=
FLUTTERWAVE_SECRET_KEY=
WALLETS_AFRICA_SECRET_KEY=
WALLETS_AFRICA_PUB_KEY=
# sandbox, api endpoints for dev, prod environments
WALLETS_API_TYPE=
FL_ENCKEY=
PAYSTACK_SECRET_KEY=